m: change to meta dir

diff --git a/ap_functions b/ap_functions
--- a/ap_functions
+++ b/ap_functions
@@ -28,6 +28,26 @@ function b() {
     fi
 }
 
+# cd to meta repo or directory
+function m() {
+    meta_dir_file=~/.meta/meta_dir
+    if [ ! -f "${meta_dir_file}" ]; then
+        echo "File ${meta_dir_file} not found."
+        return 1
+    fi
+    meta_paths="$(head -n 1 ~/.meta/meta_dir)/.meta-local/paths"
+    if [ ! -f "$meta_paths" ]; then
+        echo "File ${meta_path} not found."
+        return 1
+    fi
+    dir=$(cat "${meta_paths}" | fzf --height 40% --layout=reverse)
+    if [ ! -z "$dir" ]; then
+        cd $dir
+    else
+        echo $? > /dev/null
+    fi
+}
+
 # OK
 # edit bookmarked file
 function eb() {
